### ISSUE TITLE
Add option to cleanup unused keys to phrase push

### ISSUE THREAD

**Issue by akegan** [phrase/phrase-cli#22] opened 2020-08-04 22:10 UTC
Hello! We are new to Phrase and are just starting to use the phrase cli. We have a command setup to push updated keys to Phrase and just noticed that `phrase push` does not automatically delete unused keys.

We are able to work around this for now by using 
```
phrase uploads cleanup --id <YOUR_UPLOAD_ID>
```
as outlined in [the usage docs](https://help.phrase.com/help/usage) every time after we upload in case we've deleted keys, but it's a bit tough to extract the upload id from the response to set it up to run automatically.

Have you considered adding a flag to `phrase push` or an option that could be added to phrase.yml to run the cleanup on the upload? Does one already exist?

**Comment by ciaran-phillips** [comment] 2020-09-09 07:03
Just to add another voice - I've given this a thumbs up because I've hit exactly the same issue. Cleanup of unmentioned keys is something we normally do after every upload, and so I've got some ugly regex magic for parsing the UUID out of the response. An extra flag on `phrase push` would be great

**Comment by antonio-santos** [comment] 2021-03-17 15:16
> Just to add another voice - I've given this a thumbs up because I've hit exactly the same issue. Cleanup of unmentioned keys is something we normally do after every upload, and so I've got some ugly regex magic for parsing the UUID out of the response. An extra flag on `phrase push` would be great

Hey @ciaran-phillips can you please share your workaround solution?

**Comment by egze** [comment] 2021-09-21 11:41
We have decided to close all GitHub issues and, instead, handle them through our Customer Support. We think this shift will allow us to offer proper prioritization of issues as well as a more appropriate response time that would be expected from Phrase products.

We apologize for any inconveniences this may cause. If you believe your issue is still relevant or has a high priority, please contact support@phrase.com, and we can take more direct action toward finding a solution.

**Comment by jarrodrobins** [comment] 2021-11-21 23:49
> We have decided to close all GitHub issues and, instead, handle them through our Customer Support.

Well that's just silly. If you don't want to use GitHub, I would suggest you provide at least have a comparable offering on your website (eg a support forum), but all I can see is a "contact support" form. Removing this channel takes away transparency and inhibits discussion (see: this thread).

**Comment by Jelle-vz** [comment] 2022-05-31 11:40
I agree with @jarrodrobins. Would appreciate open communication to everyone that is looking for this.

That said; Looking for the same thing. Do we have a flag yet? :)

**Comment by forelabs** [comment] 2022-08-29 15:01
Hi everyone - sorry for not getting back here.
The decision made in the past was **wrong** and we apologize for that.

We have recognized that it is way better for developers to fire their questions directly in github where they are related to the code.
That said we have adjusted our workflow and have a custom integration so that first a customer success manager will get in touch directly within github issues. If it can not be sorted out by customer success a developer will be involved.

To get this process triggered for this issue - if it is not resolved yet - I would kindly ask to re-create an issue so that it get's into our customer success database.

Again I am sorry for the decision that was made in the past and hope that our new workflow will make everyone happy.

**Comment by jarrodrobins** [comment] 2022-08-30 03:17
Thanks for reversing @forelabs, appreciate it.

I emailed Support about this issue - apparently it's now been recorded as a feature request. 

For anyone else still reading this, in the meantime here's the script I use. I wrote it specifically for multi-module Android projects that have more than one strings file. I don't recommend using `phrase uploads cleanup` unless you are uploading only one file, otherwise you'll blow away all your translations upon subsequent uploads.

I'm sure someone can write a better Bash script than this, but it seems to work well enough. 

Make sure you're using the `tags` param in your `.phrase.yml` file to tag each uploaded file. You'll also need to set `PHRASE_ACCESS_TOKEN` and `PHRASE_PROJECT_ID` (get from your `.phrase.yml` file) as environment variables.

```
#!/bin/sh

echo "Pushing to Phrase"

phrase push --access_token $PHRASE_ACCESS_TOKEN | tee push_output

cat push_output | while read first_line; read second_line 
do
	tag=`echo $first_line | sed -n '/ *Uploading* / { s///; s/\/.*//; p; }'`
	upload_id=`echo $second_line | sed -n '/ *Check upload Id*: / { s///; s/,.*//; p; }'`

	echo "Deleting unmentioned strings from upload with id $upload_id and tag $tag"
	
	phrase keys delete-collection --project_id $PHRASE_PROJECT_ID --q "tags:$tag unmentioned_in_upload:$upload_id" --access_token $PHRASE_ACCESS_TOKEN
done

rm push_output
```

It's pretty hacky, grabbing the tag and the upload ID from the output. If the Phrase CLI output changes this will likely break.

**Comment by WaKeMaTTa** [comment] 2022-09-09 15:47
Please @forelabs can you re-open this issue.

We still wait for a solution.

Here the steps to reproduce it:

1. Create a new git branch `my-branch`
2. Add a new key in your locale YAML files.
3. Create a new phrase branch `my-branch`.
4. `phrase push --branch my-branch`.
5. Delete the key in your locale YAML files.
6. `phrase push --branch my-branch`.
7. Expectation: The key should not appear in phrase.com (branch  `my-branch`).
   Issue: The key still appears in phrase.com (branch  `my-branch`).

**Comment by JuJup** [comment] 2022-11-01 09:17
Are there any news on this issue, @forelabs?
Regarding @jarrodrobins post, it has been recorded as a feature request, but this issue still remains closed.

Would love to see this option in the CLI as the mentioned scripting solution has other downsides (when using `--use-local-branch-name`, we also have so extract the branch name somehow, before we can call the cleanup). Maybe you can give us an update and re-open this one to avoid confusion 🙏🏼

**Comment by amelie-bresson** [comment] 2023-03-07 09:01
Hi there, we're struggling with this too. It would be great to get a solution!
P.S.: One other workaround we have for this is to "Upload files" within Phrase (en-US.json, for example) when you start a translation project, instead of importing keys from GitHub via the client or the "GitHub sync". When you do that, you get a big red button called "Deleted unmentioned keys" that will delete keys from all languages if they're not present in the upload... That does the trick, but it's crazy that we cannot declare that at least in the phrase.yml config....

**Comment by senseiks** [comment] 2024-01-02 11:57
Still waiting any news on this issue, @forelabs.

**Comment by forelabs** [comment] 2024-01-02 12:00
I would like to let @theSoenke and the team take over this (since we have moved out the cli to a new team).

**Comment by jablan** [comment] 2024-01-02 12:10
Opened internal JIRA ticket (TSI-2234) to address this.

**Comment by jablan** [comment] 2024-01-10 13:26
Implemented by adding `--cleanup` option to `phrase push`.

**Closed by jablan** 2024-01-10 13:26 UTC

**Comment by malua** [comment] 2024-01-15 10:03
Hey, is cleanup doing what it's supposed to be?
When we use --cleanup on our uploads it deletes unused keys in the target language also in the base language.
Which means all untranslated keys are deleted in the base language, when we upload with --cleanup.

**Comment by jablan** [comment] 2024-01-16 08:41
@malua _keys_ are not tied to any specific language. each key can have a _translation_ in any of the project's locales (languages). cleanup works with keys, it deletes keys not mentioned in any of the uploads caused by `CLI push`.

deleting _translations_ instead is currently not supported by the CLI, and would be a separate feature request.

**Comment by malua** [comment] 2024-01-29 10:51
Ok thanks for your answer. Is it possible to add the cleanup option insde the .phraseapp.yml config file. So that the cleanup will only be executed for the base language files?

**Comment by jablan** [comment] 2024-01-29 12:02
I would decouple one feature request (support specifying `--wait` and `--cleanup` options in the config file) from the other (execute cleanup only using a single locale keys) and open new issues accordingly.

**Comment by malua** [comment] 2024-02-06 09:16
Great thanks I will do that!

**Comment by MylesWardell** [comment] 2024-12-20 06:38
Just for clarity, `phrase push --wait --cleanup` has removed all the unused keys in my source language but not in any other language. How can I delete all the keys missing a source?
